spring:
  datasource:
    url: jdbc:mysql://localhost:3306/time_attendance
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 인터페이스 명대로 별칭을 사용할 수 있게 해준다.
  type-aliases-package: com.douzone.timeattendance.domain
  # resources 밑에 mapper 패키지 하위의 모든 xml 파일에서 sql문 날림.
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

